/* eslint-disable no-console */
// Writes docs/schiva.js: the library as one script for browsers, which defines the global `schiva` (the exports of
// src/index.js). The playground of the docs loads it. Run it (npm run build:browser) after changing the library.
// The modules are CommonJS without dependencies, so each one is wrapped in a function and required on first use.
const fs = require('fs');
const path = require('path');

const SRC = path.join(__dirname, '../src');
const OUT = path.join(__dirname, '../docs/schiva.js');

function filesOf(dir) {
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const file = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      return filesOf(file);
    }
    return entry.name.endsWith('.js') ? [file] : [];
  });
}

const { name, version } = require('../package.json');

const modules = filesOf(SRC)
  .map((file) => {
    const id = path.relative(SRC, file).split(path.sep).join('/');
    const source = fs.readFileSync(file, 'utf8');
    return `${JSON.stringify(id)}: function (module, exports, require) {\n${source}\n}`;
  })
  // standalone.js reads the version from package.json.
  .concat(`"package.json": function (module) {\nmodule.exports = ${JSON.stringify({ name, version })};\n}`)
  .join(',\n');

const out = `/*! schiva ${version} | MIT license | https://schiva.js.org */
// Generated by scripts/build-browser.js (npm run build:browser): do not edit.
(function (root) {
  'use strict';
  var modules = {
${modules}
  };
  var cache = {};
  function resolve(from, request) {
    var parts = from.split('/').slice(0, -1).concat(request.split('/'));
    var stack = [];
    parts.forEach(function (part) {
      if (part === '..') {
        stack.pop();
      } else if (part !== '.' && part !== '') {
        stack.push(part);
      }
    });
    var id = stack.join('/');
    if (modules[id]) {
      return id;
    }
    if (modules[id + '.js']) {
      return id + '.js';
    }
    if (modules[id + '/index.js']) {
      return id + '/index.js';
    }
    throw new Error('schiva: cannot find module ' + request + ' from ' + from);
  }
  function load(id) {
    if (!cache[id]) {
      var module = { exports: {} };
      cache[id] = module;
      modules[id].call(module.exports, module, module.exports, function (request) {
        return load(resolve(id, request));
      });
    }
    return cache[id].exports;
  }
  root.schiva = load('index.js');
})(typeof globalThis !== 'undefined' ? globalThis : this);
`;

fs.writeFileSync(OUT, out);
console.log(`Wrote docs/schiva.js (${Math.round(out.length / 1024)} KB)`);
